export const MOCK_PRODUCTS = [
  { id: 'mock1', name: 'Apple AirPods Pro (2nd Generation)', price: 18500, stock: 12, is_available: true, product_images: [], categories: { id: 'electronics', name: 'Electronics' }, profiles: { full_name: 'Dawit Tadesse', trust_score: 95 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Premium wireless earbuds with Active Noise Cancellation and Adaptive Transparency.' },
  { id: 'mock2', name: 'Samsung 55" 4K Smart UHD TV', price: 65000, stock: 3, is_available: true, product_images: [], categories: { id: 'electronics', name: 'Electronics' }, profiles: { full_name: 'Sara Mengistu', trust_score: 88 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Crystal clear 4K UHD smart TV with vibrant colors and smart features.' },
  { id: 'mock3', name: "Nike Air Force 1 '07 White Sneakers", price: 8200, stock: 25, is_available: true, product_images: [], categories: { id: 'fashion', name: 'Fashion & Beauty' }, profiles: { full_name: 'Dawit Tadesse', trust_score: 95 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Classic white sneakers, perfect for everyday wear.' },
  { id: 'mock4', name: 'MacBook Air M2 256GB Midnight', price: 115000, stock: 1, is_available: true, product_images: [], categories: { id: 'office-tech', name: 'Office & Tech' }, profiles: { full_name: 'Helen Bekele', trust_score: 100 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Supercharged by M2. Incredibly thin and light.' },
  { id: 'mock5', name: 'Sony WH-1000XM5 Wireless Headphones', price: 22000, stock: 8, is_available: true, product_images: [], categories: { id: 'electronics', name: 'Electronics' }, profiles: { full_name: 'Abel Girma', trust_score: 91 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Industry-leading noise canceling headphones.' },
  { id: 'mock6', name: 'Dyson V15 Detect Cordless Vacuum', price: 48000, stock: 2, is_available: true, product_images: [], categories: { id: 'home-living', name: 'Home & Living' }, profiles: { full_name: 'Marta Alemu', trust_score: 84 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Powerful, intelligent cordless vacuum.' },
  { id: 'mock7', name: "Levi's 501 Original Fit Jeans", price: 5500, stock: 30, is_available: true, product_images: [], categories: { id: 'fashion', name: 'Fashion & Beauty' }, profiles: { full_name: 'Yonas Haile', trust_score: 78 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'The blueprint for every pair of jeans in existence.' },
  { id: 'mock8', name: 'Instant Pot Duo 7-in-1 Pressure Cooker', price: 9800, stock: 7, is_available: true, product_images: [], categories: { id: 'home-living', name: 'Home & Living' }, profiles: { full_name: 'Helen Bekele', trust_score: 100 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: '7-in-1 multi-functional cooker.' },
  { id: 'mock9', name: 'GoPro HERO12 Black Action Camera', price: 32000, stock: 4, is_available: true, product_images: [], categories: { id: 'electronics', name: 'Electronics' }, profiles: { full_name: 'Sara Mengistu', trust_score: 88 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Incredible image quality and video stabilization.' },
  { id: 'mock10', name: 'KitchenAid Stand Mixer 5Qt', price: 27000, stock: 5, is_available: true, product_images: [], categories: { id: 'home-living', name: 'Home & Living' }, profiles: { full_name: 'Dawit Tadesse', trust_score: 95 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Iconic stand mixer for all your baking needs.' },
  { id: 'mock11', name: 'Adidas Ultraboost 22 Running Shoes', price: 12500, stock: 14, is_available: true, product_images: [], categories: { id: 'fashion', name: 'Fashion & Beauty' }, profiles: { full_name: 'Abel Girma', trust_score: 91 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Comfortable running shoes with responsive cushioning.' },
  { id: 'mock12', name: 'Anker 65W Nano USB-C Fast Charger', price: 2800, stock: 50, is_available: true, product_images: [], categories: { id: 'electronics', name: 'Electronics' }, profiles: { full_name: 'Yonas Haile', trust_score: 78 }, shopper_profiles: { verification_status: 'verified' }, created_at: new Date().toISOString(), description: 'Fast, compact charging for all your devices.' },
]
